### ISSUE TITLE
Install Events Callendar plugin into pyatl.dev

### ISSUE THREAD

**Issue by dcsim0n** [pyatl/shovel#12]
Based on discussion in #8, The Events Calendar plugin needs to be installed in pyatl.dev wordpress. 
https://wordpress.org/plugins/the-events-calendar/

**Comment by prakesome** [comment]
Installed plugin and working on config

**Comment by prakesome** [comment]
Found a plugin to also import events from meetup. We just need the API key!
Ive installed it and is ready to be configured
