### ISSUE TITLE
Take inventory of group digital assets / accounts

### ISSUE THREAD

**Issue by prakesome** [pyatl/shovel#18]
- [ ] Enumerate digital assets
- [ ] identify who owns accounts to services and what level does the account have (ACLs)

**Comment by dcsim0n** [comment]
I can work on this.

**Comment by dcsim0n** [comment]
Known accounts
1. Discord
2. Meetup
3. Twitter
4. Wordpress / Web Hosting

**Comment by dcsim0n** [comment]
Need to talk to JR about credentials for most of the accounts listed above.

**Comment by dcsim0n** [comment]
I've created this document to list the account owners for the various pyatl accounts. https://docs.google.com/document/d/1WPiBNC_FU-KYR3QAAq18dp35N1mxfx26Df1CnuZNyzc/edit?usp=sharing

I reached out to JR on discord, waiting on a response.

**Comment by prakesome** [comment]
When JR responds with more context we can close. <- DNA
