### ISSUE TITLE
Create an page from shovel #17 to add to the text in that ticket

### ISSUE THREAD

**Issue by HasturDev** [pyatl/shovel#25]
Use this text
https://docs.google.com/document/d/1iEz50EDKwEqSZIBbwSuTlii2q_wrHztnd7edch7i8jQ/edit?usp=sharing
and create some kind of infographic or handout that we can mimic on the website

**Comment by HasturDev** [comment]
This will be a page on the website that can be converted into a pdf to handout at meetups
Images should be free to use images. No violation of copyright nonsense

**Comment by dcsim0n** [comment]
First draft of the content is here:

https://pyatl.dev/?p=177&preview=true

My account doesn't have access to create "pages" so this is a "post" for now.

**Comment by prakesome** [comment]
pyatl.dev/partner-program

Name of Page: "Partner Program"
