### ISSUE TITLE
Figure out how to get people from meetup into pyatl.dev website

### ISSUE THREAD

**Issue by prakesome** [pyatl/shovel#3]
Need to figure out a way to get people onto our website.
This will allow us greater contact with the community directly.

**Comment by HasturDev** [comment]
Could we just make a QR code that leads people to the website that we flash at every meetup?

**Comment by prakesome** [comment]
Yes, we code that we can also post everywhere else. Even in meetup itself On Nov 29, 2023, at 11:07 PM, Ian Mizer ***@***.***> wrote:﻿
Could we just make a QR code that leads people to the website that we flash at every meetup?

**Comment by prakesome** [comment]
@HasturDev There is this plugin to generate QR codes in wordpress https://wordpress.org/plugins/master-qr-generator/
We can use it to generate a QR to an landing page within the website itself inviting people to join the group.

Can also generate a QR code per post/page. Useful for sharing links to content on the site.

**Comment by dcsim0n** [comment]
Notes about what "done" will look like:
- List of emails, names, and any other contact info that meetup allows. We want to make our own mailing list
- Once meetup export is done, we can start marketing with a newsletter

**Comment by prakesome** [comment]
I found a way to send emails through meetup that allows us to contact all the group members on meetup. It also allows us to include links in the message.
