### ISSUE TITLE
Setup survey around why people are part of pyatl

### ISSUE THREAD

**Issue by prakesome** [pyatl/shovel#33]
- define survey
- build/setup form to collect info
- schedule survey
- promote it
- run it

**Comment by prakesome** [comment]
I initially built the survey form with the form plugin we have.
The form plugin does not have good  spam protection and we were getting some spam to our email addresses.
I took the survey post offline and am researching how to improve the spam protection for the form plugin.
Docs for plugin: https://contactform7.com/docs/
See if theres a way to get the captcha in the free version

**Comment by dcsim0n** [comment]
Hello!

**Comment by dcsim0n** [comment]
1. Google’s reCAPTCHA3 is a high quality and popular solution for handling human verification in wordpress.
2. Google recaptcha3 is free up to 1 Million verification per month
3. I created access tokens in google's recaptcha admin panel, but can not install them into pyatl.dev without admin permissions.
5. Instructions for how to configure reCAPTCHA for contact form 7 are here: https://contactform7.com/recaptcha/
6. I can walk @pryelluw  or @HasturDev  through the configuration during the next meeting if you want.

**Comment by prakesome** [comment]
TODO:

- Send pablo captcha keys as a secret to email (one time email thingy)
- Pablo will setup captcha field settings
- Pablo will add the captcha field to the forms

**Comment by dcsim0n** [comment]
email sent w/ api keys

**Comment by prakesome** [comment]
Pablo has got the captcha keys now. Will update

**Comment by prakesome** [comment]
Added captcha keys.

**Comment by prakesome** [comment]
done!
