### ISSUE TITLE
Organize online content (youtube, etc) production/streaming

### ISSUE THREAD

**Issue by prakesome** [pyatl/shovel#42]

**Comment by prakesome** [comment]
So Mike (@xycia on discord) offered to record and upload talks for us. He would need:

- Access to our channel as an editor
  - Do we have a channel?

I know @HasturDev was the one handling this stuff. So ill assign it to him.

We already have the two talks from the March 2024 event recorded and available

The one by Leslie
https://www.youtube.com/watch?v=SGuMB-vSH-4

The one by Jimmy
https://www.youtube.com/watch?v=KIWh35-4HLw

Both are unlisted

**Comment by prakesome** [comment]
Create new YT account with pyatl.dev email address like yt@pyatl.dev and make others editors

**Comment by prakesome** [comment]
Created a new email address social AT pyatl.dev

Created a new youtube account for this email https://www.youtube.com/@pyatl

Made @JVthearchitect an editor of the account

Asked Mike to share his email in order to add him as an editor as well.

**Comment by prakesome** [comment]
@JVthearchitect confirm you have access in order to move this to done

**Comment by JVthearchitect** [comment]
@prakesome Confirmed! I received the email and accepted the invite.

**Comment by prakesome** [comment]
Added Mike as editor and sent him the invite. 
He will upload videos as time allows.
