### ISSUE TITLE
Define mission statement or copy it over from website

### ISSUE THREAD

**Issue by prakesome** [pyatl/shovel#5]
Current "mission statement":

PyAtl meets every month in Atlanta for presentations and discussion about [Python](http://python.org/), the powerful and easy-to-use programming language.

**Comment by prakesome** [comment]
Our reason for existence is to have a forum/place/network for pythonistas to meet/talk/collab about everything python.

**Comment by prakesome** [comment]
@dcsim0n

See https://docs.google.com/presentation/d/1vUCauRSgNrcxz6wZghXFRb1KUe34hev-M444y8_A9Dk/edit?usp=sharing

**Comment by HasturDev** [comment]
closing
